version: "3.8"
services:
    psdatabase:
        container_name: pseshop
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=eshop
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=eshop_backend
        ports:
            - "5002:5432"
        volumes:
            - psdatabase:/var/lib/postgresql/data
volumes:
    psdatabase:

